// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

/*
Package controller is a generated protocol buffer package.

It is generated from these files:
	stream.proto

It has these top-level messages:
	AppendRequest
	AppendReply
*/
package controller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type AppendRequest struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Sync    bool   `protobuf:"varint,2,opt,name=sync" json:"sync,omitempty"`
}

func (m *AppendRequest) Reset()                    { *m = AppendRequest{} }
func (m *AppendRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()               {}
func (*AppendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppendRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *AppendRequest) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

// The response message containing the greetings
type AppendReply struct {
	Offset string `protobuf:"bytes,1,opt,name=offset" json:"offset,omitempty"`
}

func (m *AppendReply) Reset()                    { *m = AppendReply{} }
func (m *AppendReply) String() string            { return proto.CompactTextString(m) }
func (*AppendReply) ProtoMessage()               {}
func (*AppendReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendReply) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func init() {
	proto.RegisterType((*AppendRequest)(nil), "controller.AppendRequest")
	proto.RegisterType((*AppendReply)(nil), "controller.AppendReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StreamController service

type StreamControllerClient interface {
	// Sends a greeting
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendReply, error)
}

type streamControllerClient struct {
	cc *grpc.ClientConn
}

func NewStreamControllerClient(cc *grpc.ClientConn) StreamControllerClient {
	return &streamControllerClient{cc}
}

func (c *streamControllerClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendReply, error) {
	out := new(AppendReply)
	err := grpc.Invoke(ctx, "/controller.StreamController/Append", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StreamController service

type StreamControllerServer interface {
	// Sends a greeting
	Append(context.Context, *AppendRequest) (*AppendReply, error)
}

func RegisterStreamControllerServer(s *grpc.Server, srv StreamControllerServer) {
	s.RegisterService(&_StreamController_serviceDesc, srv)
}

func _StreamController_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamControllerServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.StreamController/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamControllerServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.StreamController",
	HandlerType: (*StreamControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _StreamController_Append_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream.proto",
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x29, 0x4a,
	0x4d, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xce, 0xcf, 0x2b, 0x29, 0xca,
	0xcf, 0xc9, 0x49, 0x2d, 0x52, 0xb2, 0xe5, 0xe2, 0x75, 0x2c, 0x28, 0x48, 0xcd, 0x4b, 0x09, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x85, 0x84, 0xb8, 0x58, 0x8a, 0x2b, 0xf3,
	0x92, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x82, 0xc0, 0x6c, 0x25, 0x55, 0x2e, 0x6e, 0x98, 0xf6,
	0x82, 0x9c, 0x4a, 0x21, 0x31, 0x2e, 0xb6, 0xfc, 0xb4, 0xb4, 0xe2, 0xd4, 0x12, 0xb0, 0x5e, 0xce,
	0x20, 0x28, 0xcf, 0x28, 0x88, 0x4b, 0x20, 0x18, 0xec, 0x02, 0x67, 0xb8, 0xcd, 0x42, 0x76, 0x5c,
	0x6c, 0x10, 0xad, 0x42, 0x92, 0x7a, 0x08, 0x07, 0xe9, 0xa1, 0xb8, 0x46, 0x4a, 0x1c, 0x9b, 0x54,
	0x41, 0x4e, 0xa5, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x33, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0x73, 0xc8, 0x18, 0xdc, 0x00, 0x00, 0x00,
}
